version: '3.8'

services:
  web:
    build: .
    container_name: bsbi_search_engine
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./index:/app/index
    environment:
      - DATA_DIR=/app/data
      - INDEX_DIR=/app/index
      - FLASK_DEBUG=False
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
